export enum DomaineExpertise {
    DEVELOPPEMENT_LOGICIEL = "DÉVELOPPEMENT LOGICIEL",
    CONCEPTION_GRAPHIQUE = "CONCEPTION GRAPHIQUE",
    REDACTION_ET_EDITION = "RÉDACTION ET ÉDITION",
    MARKETING_NUMERIQUE = "MARKETING NUMÉRIQUE",
    TRADUCTION_ET_LOCALISATION = "TRADUCTION ET LOCALISATION",
    CONSULTING_ET_GESTION_DE_PROJET = "CONSULTING ET GESTION DE PROJET",
    VIDEO_ET_ANIMATION = "VIDÉO ET ANIMATION",
    CONCEPTION_DE_BASES_DE_DONNEES = "CONCEPTION DE BASES DE DONNÉES",
    SERVICES_INFORMATIQUES = "SERVICES INFORMATIQUES",
    SCIENCES_DES_DONNEES_ET_INTELLIGENCE_ARTIFICIELLE = "SCIENCES DES DONNÉES ET INTELLIGENCE ARTIFICIELLE",
    SEO = "SEO",
  }
  
