export enum DomaineExpertise {
    DEVELOPPEMENT_LOGICIEL = "DEVELOPPEMENT_LOGICIEL",
    CONCEPTION_GRAPHIQUE = "CONCEPTION_GRAPHIQUE",
    REDACTION_ET_EDITION = "REDACTION_ET_EDITION",
    MARKETING_NUMERIQUE = "MARKETING_NUMERIQUE",
    TRADUCTION_ET_LOCALISATION = "TRADUCTION_ET_LOCALISATION",
    CONSULTING_ET_GESTION_DE_PROJET = "CONSULTING_ET_GESTION_DE_PROJET",
    VIDEO_ET_ANIMATION = "VIDEO_ET_ANIMATION",
    CONCEPTION_DE_BASES_DE_DONNEES = "CONCEPTION_DE_BASES_DE_DONNEES",
    SERVICES_INFORMATIQUES = "SERVICES_INFORMATIQUES",
    SCIENCES_DES_DONNEES_ET_INTELLIGENCE_ARTIFICIELLE = "SCIENCES_DES_DONNEES_ET_INTELLIGENCE_ARTIFICIELLE",
    SEO = "SEO",
  }
  
