export enum ExperienceEnum  {
    ONE_TO_TWO_YEARS ='ONE_TO_TWO_YEARS',
    TWO_TO_THREE_YEARS='TWO_TO_THREE_YEARS',
    THREE_TO_SIX_YEARS='THREE_TO_SIX_YEARS',
    SIX_MORE_YEARS='THREE_TO_SIX_YEARS',
  }