export enum NatureTravailEnum  {
    FULL_TIME= 'FULL_TIME',
    PART_TIME= 'PART_TIME',
    CONTRACT='CONTRACT',
    FREELANCE= 'FREELANCE',
    INTERNSHIP= 'INTERNSHIP',
    TEMPORARY= 'TEMPORARY',
    OTHER='OTHER',
  }