export enum Technologie {

    PHOTOSHOP = "PHOTOSHOP",
    ORACLE = "ORACLE",
    JAVA = "JAVA",
    C_PLUS_PLUS = "C++",
    PYTHON = "PYTHON",
    JAVASCRIPT = "JAVASCRIPT",
    HTML_CSS = "HTML/CSS",
    REACT = "REACT",
    ANGULAR = "ANGULAR",
    SPRING = "SPRING",
    NODE_JS = "NODE.JS",
    ANDROID = "ANDROID",
    IOS = "IOS",
    DJANGO = "DJANGO",
    FLASK = "FLASK",
    RUBY = "RUBY",
    PHP = "PHP",
    SEO = "SEO",
}
